engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 45
        javascript:
    exclude_paths:
      - 'config/**/*'
      - 'db/**/*'
      - 'spec/**/*'
      - '**/*.js'
  fixme:
    enabled: true
  markdownlint:
    enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-48
    config:
      file: config/rubocop.yml
  tslint:
    enabled: true
    channel: beta
    config: config/tslint.json

ratings:
   paths:
   - Gemfile.lock
   - '**.md'
   - '**.rb'
   - '**.ts'

exclude_paths:
- 'bin/**/*'
- 'log/**/*'
- 'node_modules/**/*'