env:
  global:
    - CC_TEST_REPORTER_ID=cb7faf522523bcf26d3608e1efb979c0f3e2d32c3309a2350a8a60e963924dc5
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
language: ruby
sudo: false

branches:
  except:
    - gh-pages

cache:
  - bundler
  - yarn

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

services:
  - postgresql

bundler_args: --without production

before_install:
  - nvm install node
  - npm install -g yarn

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - yarn
  - RAILS_ENV=test bin/rails db:migrate --trace
  - RAILS_ENV=test bin/rails db:seed

script:
  - yarn test
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $? || true; fi

notifications:
  email: false
