language: ruby
sudo: false

branches:
  except:
    - gh-pages

cache:
  - bundler
  - yarn

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

services:
  - postgresql

bundler_args: --without production

before_install:
  - nvm install node
  - npm install -g yarn

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - yarn
  - RAILS_ENV=test bin/rails db:migrate --trace
  - RAILS_ENV=test bin/rails db:seed

script:
  - yarn test:all

notifications:
  email: false
