version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: yarn start
    volumes:
      - .:/myapp
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
