development:
  adapter: async

test:
  adapter: async

preview:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: strafforts_preview

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: strafforts_production
