AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '**/application_helper.rb'
  TargetRubyVersion: 2.0
Documentation:
  Enabled: false
Metrics/AbcSize:
  Max: 50
Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - 'spec/**/*.rb'
Metrics/ClassLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'
Style/NumericLiterals:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
