AllCops:
  Exclude:
    - '**/application_helper.rb'
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'
    - 'test/test_helper.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5
Documentation:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Metrics/AbcSize:
  Max: 50
Metrics/BlockLength:
  Exclude:
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
Metrics/ClassLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - "db/migrate/*.rb"
Style/FormatStringToken:
  EnforcedStyle: template
Style/DateTime:
  Enabled: false
Style/NumericLiterals:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
