app:
  name: 'Strafforts'
  contact_url: 'http://yizeng.me/#contact'
  demo_path: '/athletes/yizeng'
  description: 'A Visualizer for Strava Estimated Best Efforts and Races'
  html_meta_description: 'Strafforts, a visualizer for Strava Estimated Best Efforts and Races, which calls Strava API to fetch estimated best efforts and races and visualize them in data tables, line charts and pie charts.'
  html_meta_keywords: 'strava,bestefforts,running,activity,visualizer,races,strafforts'
  production_url: 'http://www.strafforts.com'
  title: 'Strafforts - A Visualizer for Strava Estimated Best Efforts and Races'
  version: 'v0.4.2'
strava:
  api_auth_authorize_url: 'http://www.strava.com/oauth/authorize'
  api_auth_token_url: 'https://www.strava.com/oauth/token'
  api_auth_deauthorize_url: 'https://www.strava.com/oauth/deauthorize'
  api_client_id: <%= ENV['STRAVA_API_CLIENT_ID'] %>
  athletes_base_url: 'https://www.strava.com/athletes'
