app:
  name: 'Strafforts'
  contact_url: 'http://yizeng.me/#contact'
  demo_path: '/athletes/9123806'
  description: 'An Analytics Web App for Strava Estimated Best Efforts and Races'
  html_meta_description: 'An analytics web app that allow athletes to analyze their visualized Strava estimated best efforts and races data in tables and charts.'
  html_meta_description_for_athletes: 'Visualized Strava estimated best efforts and races data for '
  html_meta_keywords: 'strava,strafforts,bestefforts,races,running,data,visualizer,analytics'
  production_url: 'http://www.strafforts.com'
  title: 'Strafforts - An Analytics Web App for Strava Estimated Best Efforts and Races'
  global_message: <%= ENV['GLOBAL_MESSAGE'] %>
  version: <%= ENV['APP_VERSION'] %>
strava:
  api_auth_authorize_url: 'https://www.strava.com/oauth/authorize'
  api_auth_deauthorize_url: 'https://www.strava.com/oauth/deauthorize'
  api_auth_token_url: 'https://www.strava.com/oauth/token'
  api_client_id: <%= ENV['STRAVA_API_CLIENT_ID'] %>
  athletes_base_url: 'https://www.strava.com/athletes'
